name = "pouyakarimi"
compatibility_date = "2026-09-01"
routes = [
  { pattern = "pouyakarimi.com", custom_domain = true },
  { pattern = "www.pouyakarimi.com", custom_domain = true },
]

[assets]
directory = "./public"
